### ISSUE TITLE
How should eFFORT be cited?

### ISSUE THREAD

**Issue by sognetic** [b2-hive/eFFORT#12]
Given that first Belle II results using eFFORT will soon be published maybe it makes sense to give some way to cite this tool? Would Zenodo be an option?

**Comment by MarkusPrim** [comment]
That is a good option. We are currently thinking about the best way forward. There will also be a eFFORT related paper which could serve as reference in the future.

**Comment by MarkusPrim** [comment]
https://zenodo.org/record/3965699
